// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
//
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import Footer from "@/components/Footer";

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <head>
            <meta property="og:title" content="TEUS Group Team"/>
            <meta property="og:description" content="This is an online business card website for Teus Group employees."/>
            <meta property="og:url" content="https://card.teus-group.com"/>
            <meta property="og:type" content="website"/>
            <meta property="og:image" content="https://card.teus-group.com/card_list_header.jpg"/>


            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <link rel="icon" href="/favicon.png"/>
            <link rel="stylesheet" href="https://use.typekit.net/kgl5wdb.css"/>
            <title>Business Card</title>
        </head>
        <body>
        <main>{children}</main>
        <Footer/>
        </body>
        </html>
    );
}

